# Generated by Django 4.0.2 on 2022-02-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(default='')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_on', models.DateField()),
                ('category', models.CharField(max_length=30)),
                ('true_label', models.CharField(max_length=30)),
                ('false_label', models.CharField(max_length=30)),
            ],
        ),
    ]
