# Generated by Django 3.2.14 on 2022-08-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(default='')),
                ('resolution', models.TextField(default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=30)),
                ('true_label', models.CharField(max_length=30)),
                ('false_label', models.CharField(max_length=30)),
                ('true_price', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('false_price', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('volume', models.IntegerField(default=0)),
            ],
        ),
    ]
