# Generated by Django 4.0.2 on 2022-02-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='false_price',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='event',
            name='resolution',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='true_price',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='event',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
