# Generated by Django 4.0.2 on 2022-02-22 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('M', 'Market'), ('P', 'Price')], max_length=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('outcome', models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=2)),
                ('direction', models.CharField(choices=[(1, 'Buy'), (0, 'Sell')], max_length=2)),
                ('system_price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('system_direction', models.CharField(choices=[(1, 'Buy'), (0, 'Sell')], max_length=2)),
                ('time', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
