# Generated by Django 4.0.2 on 2022-02-24 04:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('M', 'Market'), ('P', 'Price')], max_length=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MaxValueValidator(1, message='Price must be less than $1.00'), django.core.validators.MinValueValidator(0, message='Price must be positive')])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Must order at least one unit.')])),
                ('pending_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Order amount cannot be below 0.')])),
                ('filled_quantity', models.IntegerField(default=0)),
                ('outcome', models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=2)),
                ('direction', models.CharField(choices=[(1, 'Buy'), (-1, 'Sell')], max_length=2)),
                ('time', models.DateTimeField(auto_now=True)),
                ('system_price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('system_direction', models.CharField(choices=[(1, 'Buy'), (-1, 'Sell')], max_length=2)),
                ('completed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
