# Generated by Django 3.2.14 on 2022-08-01 14:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('M', 'Market'), ('P', 'Price')], max_length=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MaxValueValidator(1, message='Price must be less than $1.00'), django.core.validators.MinValueValidator(0, message='Price must be positive')])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Must order at least one unit.')])),
                ('pending_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Order amount cannot be below 0.')])),
                ('filled_quantity', models.IntegerField(default=0)),
                ('pending_funds', models.DecimalField(decimal_places=2, max_digits=100)),
                ('outcome', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('direction', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=10)),
                ('time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('OPEN', 'Open'), ('CACNCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
