# Generated by Django 4.0.2 on 2022-02-22 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_alter_order_system_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='system_direction',
            field=models.CharField(choices=[(1, 'Buy'), (0, 'Sell')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
