# Generated by Django 4.0.2 on 2022-02-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_system_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='system_direction',
        ),
        migrations.RemoveField(
            model_name='order',
            name='system_price',
        ),
    ]
