# Generated by Django 4.0.2 on 2022-02-23 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_system_direction_order_system_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Must order at least 1 unit.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='direction',
            field=models.CharField(choices=[(1, 'Buy'), (-1, 'Sell')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MaxValueValidator(1, message='Price must be less than $1.00'), django.core.validators.MinValueValidator(0, message='Price must be positive')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='system_direction',
            field=models.CharField(choices=[(1, 'Buy'), (-1, 'Sell')], max_length=2),
        ),
    ]
