# Generated by Django 3.2.14 on 2022-08-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderBook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbook',
            old_name='order_id',
            new_name='order',
        ),
    ]
